name = input("이름을 입력하세요: ")
studentNumber = input("학번을 입력하세요: ")
lesson = input("학과를 입력하세요: ")
school = input("학교를 입력하세요: ")
grade = input("학년을 입력하세요: ")

print("이름:", name)
print("학번:", studentNumber)
print("학과:", lesson)
print("학교:", school)
print("학년:", grade)